### PR TITLE
Fix classloading crash with ASM

### LINKED ISSUE #1415: Incompatible with mods that modify the Inventory GUI
### GregTech CEu Version

2.5

### Modpack Used

no

### Addons Installed

[Mini Effects (Forge)](https://www.curseforge.com/minecraft/mc-mods/mini-effects)

### Environment

anyway

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

just load mini effects and GTCEu.

### Crash Report

Can not to get CR but find the mixins error in the log:
https://pastebin.com/u2YbED5k

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TechLord22**
## What
This PR fixes a crash related to classloading issues when checking `Loader#isModLoaded` during ASM transformation. `Loader` is unable to determine if a mod is loaded properly, and may crash in attempting to do so, this early in loading. For mods that run server side, an alternative means of checking is used, like NuclearCraft is checked presently. For client side only mods, a class from the target mod must be checked if present instead.

## Outcome
Fixes classloading crash with ASM Transformers. Closes #1415.

### CODE REVIEW

File: src/main/java/gregtech/asm/GregTechTransformer.java [hunk 1]
```diff
@@ -120,7 +121,8 @@ public byte[] transform(String name, String transformedName, byte[] basicClass)
                 ClassReader classReader = new ClassReader(basicClass);
                 ClassWriter classWriter = new ClassWriter(0);
 
-                ModContainer container = Loader.instance().getIndexedModList().get("nuclearcraft");
+                // fix NC recipe compat different depending on overhaul vs underhaul
+                ModContainer container = Loader.instance().getIndexedModList().get(GTValues.MODID_NC);
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/asm/GregTechTransformer.java:125]: Do we need to null check this `get` call in case NC is not in the mod list?

Comment (TechLord22) [reply src/main/java/gregtech/asm/GregTechTransformer.java:125]: We shouldn't need to here, since this case for the switch statement will only execute when the target class for NC is passed into the transformer, and is therefore loaded/present.

**Review by ALongStringOfNumbers — APPROVED** [review]
