### PR TITLE
Show name of locked fluid in Quantum Tank

### LINKED ISSUE #1693: Empty locked super & quantum tank does not show locked fluid
### GregTech CEu Version

v2.6

### Modpack Used

Nomi CEu

### Addons Installed

GTFO v1.8.6

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

Locked tank show what fluid it will only store:

### Actual Behavior

The locked tank shows nothing when it's empty :

### Steps to Reproduce

Step 1: Put any fluid in and turn on lock mode
Step 2: Empty the tank

### Additional Information

Although the locked tank shows nothing, it's still remember the fluid that it is locked to:

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
## What
Always shows the fluid name of locked fluids on Quantum Tanks, even when all fluid has been extracted, but the tank is still locked. Closes #1693 

## Outcome
Always show locked fluid information on quantum tanks

### CODE REVIEW

File: src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java [hunk 1]
```diff
@@ -323,6 +326,22 @@ protected ModularUI createUI(EntityPlayer entityPlayer) {
                 .build(getHolder(), entityPlayer);
     }
 
+    private Consumer<List<ITextComponent>> getFluidNameText(TankWidget tankWidget) {
+        return (list) -> {
+            String fluidName = tankWidget.getFluidLocalizedName().isEmpty() ? this.lockedFluid != null ? this.lockedFluid.getLocalizedName() : "" : tankWidget.getFluidLocalizedName();
```
Comment (TechLord22) [inline src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java:331]: In the cases where this ternary and the one below result in `""`, should adding to the list be prevented entirely, instead of adding the empty string?

**Review by TechLord22 — COMMENTED** [review]
Unraveling these ternaries into regular if statements would be appreciated.

**Review by TechLord22 — APPROVED** [review]
