### PR TITLE
Explosion config Overhaul

### LINKED ISSUE #958: [BUG] Steam Boiler only Explodes when the Overvoltage Explosion config is on
**Describe the bug**
following codes shows the steam boiler explosion is handled by the [machines.doExplosions](https://github.com/GregTechCEu/GregTech/blob/b0967895d05c6c63ae6aef0efbdc721dbf5a972c/src/main/java/gregtech/common/ConfigHolder.java#L77-L78) config
since steam boiler contains no power, it needs to be fixed (I'm fixing it!)
https://github.com/GregTechCEu/GregTech/blob/236eba02edb6c7cc95a81735af69f65ec7b3004c/src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java#L228-L229
https://github.com/GregTechCEu/GregTech/blob/53aa97a024598ed04990a2b02a356feaec8d800f/src/main/java/gregtech/api/metatileentity/MetaTileEntity.java#L1360-L1364

**Versions**
GTCEu: 2.2.3

**Setup**
dev env

### PR DESCRIPTION
**Pull request by Quarri6343**
**What:**
This PR
・fix inappropriate doExplosion config description
・add a new config option called doEnvironmentExplosion  that allows machines set on Fire and explode in Rain, Fire, Water or Lava

**Implementation Details:**
・I edited configHolder
・I added a new method called checkEnvironmentExplosion in TieredMetaTileEntity and MetaTileEntityEnergyHatch class to allow machines explode in certain environment
Its explosion condition is from GT5u
It won't be called if the explosion config is off
・I added a new method called getEnvironmentResistance
it should return true if the machine has resistance to certain environment
・I added a informative tooltip for some machines which have Environment Resistance
・I added a new argument in the existing doExplosion method to allow environment explosion can also be handled by it

**Outcome:**
fixes #958
gives more challenges to experienced GT players

**Additional info:**
Multiblocks Controller itself does not explode unless its Energy Hatch explodes

**Possible compatibility issue:**
If any addon implements solar panels, they must override getEnvironmentResistance in their class to prevent explosion when the config is enabled

### CODE REVIEW

File: src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java [hunk 1]
```diff
@@ -68,6 +86,47 @@ public void renderMetaTileEntity(CCRenderState renderState, Matrix4 translation,
...
+                    if (block == Blocks.FIRE || block == Blocks.WATER || block == Blocks.FLOWING_WATER || block == Blocks.LAVA || block == Blocks.FLOWING_LAVA) {
+                        doExplosion(tier, true);
+                        return;
+                    }
+                }
+            }
+            if (world.rand.nextInt(1000) == 0) {
+                if (world.isRainingAt(getPos()) || world.isRainingAt(getPos().east()) || world.isRainingAt(getPos().west()) || world.isRainingAt(getPos().north()) || world.isRainingAt(getPos().south())) {
+                    if (world.isThundering() && world.rand.nextInt(3) == 0) {
+                        doExplosion(tier, true);
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java:112]: Hm, I think that the terrain damage here should still respect the config option `doExplosion`. All the config option does is determine if the terrain is damaged when the machine explodes, it will explode on either config option.

File: src/main/java/gregtech/common/ConfigHolder.java [hunk 2]
```diff
@@ -74,9 +74,12 @@ public static class MachineOptions {
         @Config.Comment({"Steam to EU multiplier for Steam Multiblocks.", "1.0 means 1L Steam -> 1 EU. 0.5 means 2L Steam -> 1 EU.", "Default: 0.5"})
         public double multiblockSteamToEU = 0.5;
 
-        @Config.Comment({"Whether machines should explode when overloaded with power.", "Default: true"})
+        @Config.Comment({"Whether machines or boilers should explode when overloaded with power or met special conditions.", "Default: true"})
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/common/ConfigHolder.java:77]: Could you change this config option to say "... explode causing terrain damage when overloaded ..."

**Comment by Quarri6343** [comment]
Thanks for the review!
`All the config option does is determine if the terrain is damaged when the machine explodes`
I changed the config name to doExplosionDamagesTerrain to avoid future confusion
`Could you change this config option to say "... explode causing terrain damage when overloaded ..."`
I did a slightly different approach to fix the description but it should tell the same thing

I also changed _Environment_ to _Terrain_
Its my bad

File: src/main/java/gregtech/api/metatileentity/MetaTileEntity.java [hunk 3]
```diff
@@ -1360,7 +1361,16 @@ public RecipeMap<?> getRecipeMap() {
...
         getWorld().createExplosion(null, getPos().getX() + 0.5, getPos().getY() + 0.5, getPos().getZ() + 0.5,
-                explosionPower, ConfigHolder.machines.doExplosions);
+                explosionPower, ConfigHolder.machines.doExplosionDamagesTerrain);
+    }
+
+    public void setOnFire() {
+        for (EnumFacing side : EnumFacing.VALUES) {
+            if (getWorld().isAirBlock(getPos().offset(side))) {
+                getWorld().setBlockState(getPos().offset(side), Blocks.FIRE.getDefaultState(), 11);
+                return;
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/metatileentity/MetaTileEntity.java:1371]: Instead of calling `return` here, which will result in only 1 air space being turned to fire, this method could take in a double for percentage chance to turn blocks to fire. It could look something like

```java
public void setOnFire(double chance) {
        for(EnumFacing side : EnumFacing.VALUES) {
        if(chance >= GTValues.RNG.nextDouble(100.00) && getWorld.isAirBlock(getPos().offset(side))) {
        getWorld().setBlockState(getPos().offset(side), Blocks.FIRE.getDefaultState(), 11);
        }
    }
}
```

This would allow for higher tier machines a chance for setting more sides on fire at one time, if the passed chance is based on the tier of the machine.

However, this does not guarantee at least one fire spawned, so you could also change the above method and have the passed `chance` value be the chance for an additional fire to be spawned after the first fire is spawned. (I think this makes the most sense)

File: src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java [hunk 4]
```diff
@@ -68,6 +86,47 @@ public void renderMetaTileEntity(CCRenderState renderState, Matrix4 translation,
...
+            }
+        }
+    }
+
+    /**
+     * Whether this tile entity not explode in rain, fire, water or lava
+     *
+     * @return true if tile entity should not explode in these sources
+     */
+    public boolean getTerrainResistance() {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java:126]: This could be called something like `getIsWeatherOrTerrainResistant`

File: src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java [hunk 5]
```diff
@@ -68,6 +86,47 @@ public void renderMetaTileEntity(CCRenderState renderState, Matrix4 translation,
...
 
+    @Override
+    public void update() {
+        super.update();
+        if (ConfigHolder.machines.doTerrainExplosion) {
+            checkTerrainExplosion();
+        }
+    }
+
+    public void checkTerrainExplosion() {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java:97]: I would recommend `checkWeatherOrTerrainExplosion`

File: src/main/java/gregtech/common/ConfigHolder.java [hunk 6]
```diff
@@ -74,8 +74,12 @@ public static class MachineOptions {
         @Config.Comment({"Steam to EU multiplier for Steam Multiblocks.", "1.0 means 1L Steam -> 1 EU. 0.5 means 2L Steam -> 1 EU.", "Default: 0.5"})
         public double multiblockSteamToEU = 0.5;
 
-        @Config.Comment({"Whether machines should explode when overloaded with power.", "Default: true"})
-        public boolean doExplosions = true;
+        @Config.Comment({"Whether machines or boilers explosion damages terrain.",
+                "Note machines or boilers always explode when overloaded with power or met special conditions regardless this config.", "Default: true"})
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/common/ConfigHolder.java:78]: `machines and boilers` and also `or met with special conditions, regardess of....`

File: src/main/java/gregtech/common/ConfigHolder.java [hunk 7]
```diff
@@ -74,8 +74,12 @@ public static class MachineOptions {
         @Config.Comment({"Steam to EU multiplier for Steam Multiblocks.", "1.0 means 1L Steam -> 1 EU. 0.5 means 2L Steam -> 1 EU.", "Default: 0.5"})
         public double multiblockSteamToEU = 0.5;
 
-        @Config.Comment({"Whether machines should explode when overloaded with power.", "Default: true"})
-        public boolean doExplosions = true;
+        @Config.Comment({"Whether machines or boilers explosion damages terrain.",
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/common/ConfigHolder.java:77]: "Whether machines or boilers damage the terrain when they explode"

File: src/main/java/gregtech/common/ConfigHolder.java [hunk 8]
```diff
@@ -74,8 +74,12 @@ public static class MachineOptions {
...
+                "Note machines or boilers always explode when overloaded with power or met special conditions regardless this config.", "Default: true"})
+        public boolean doExplosionDamagesTerrain = true;
+
+        @Config.Comment({"Whether machines explode in terrain damage such as rain or fire.", "Default: false"})
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/common/ConfigHolder.java:81]: "Whether machines explode in rainy weather or when placed next to certain terrain, such as fire or lava"

File: src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java [hunk 9]
```diff
@@ -68,6 +86,47 @@ public void renderMetaTileEntity(CCRenderState renderState, Matrix4 translation,
...
+        World world = getWorld();
+        if (!world.isRemote && !getTerrainResistance() && energyContainer.getEnergyStored() != 0) {
+            if (world.rand.nextInt(1000) == 0) {
+                for (EnumFacing side : EnumFacing.VALUES) {
+                    Block block = getWorld().getBlockState(getPos().offset(side)).getBlock();
+                    if (block == Blocks.FIRE || block == Blocks.WATER || block == Blocks.FLOWING_WATER || block == Blocks.LAVA || block == Blocks.FLOWING_LAVA) {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java:103]: Not sure if water should be included here, some discussion might be necessary on this one.

File: src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityRockBreaker.java [hunk 10]
```diff
@@ -101,4 +101,9 @@ protected boolean shouldSearchForRecipes() {
             return hasValidFluids && super.shouldSearchForRecipes();
         }
     }
+
+    @Override
+    public boolean getTerrainResistance(){
+        return true;
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityRockBreaker.java:107]: This machine should also have the tooltip applied to it if the weather explosion config is true.

File: src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java [hunk 11]
```diff
@@ -154,4 +166,37 @@ public void getSubItems(CreativeTabs creativeTab, NonNullList<ItemStack> subItem
             }
         }
     }
+
+    public void checkTerrainExplosion() {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java:170]: This method could be put in GTUtility or in MTE, so you don't have to copy and paste it for both the tiered MTEs and the energy hatches.

File: src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityRockBreaker.java (hunk 10 above)
Comment (Quarri6343) [reply src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityRockBreaker.java:107]: TieredMTE class has this code so this machine already has the tooltip
```
    @Override
    public void addInformation(ItemStack stack, @Nullable World player, @Nonnull List<String> tooltip, boolean advanced) {
        super.addInformation(stack, player, tooltip, advanced);
        if (ConfigHolder.machines.doTerrainExplosion && getIsWeatherOrTerrainResistant())
            tooltip.add(I18n.format("gregtech.universal.tooltip.terrain_resist"));
    }
```

**Review by ALongStringOfNumbers — APPROVED** [review]

File: src/main/java/gregtech/api/metatileentity/MetaTileEntity.java [hunk 12]
```diff
@@ -1357,10 +1359,59 @@ public RecipeMap<?> getRecipeMap() {
         return null;
     }
 
+    public void checkWeatherOrTerrainExplosion(float explosionPower, double additionalFireChance, IEnergyContainer energyContainer) {
```
Comment (DStrand1) [inline src/main/java/gregtech/api/metatileentity/MetaTileEntity.java:1362]: I think it would be good to check the config here as well to avoid an accidental call and exit early

File: src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java [hunk 13]
```diff
@@ -68,6 +86,14 @@ public void renderMetaTileEntity(CCRenderState renderState, Matrix4 translation,
         getBaseRenderer().render(renderState, translation, colouredPipeline);
     }
 
+    @Override
+    public void update() {
+        super.update();
+        if (ConfigHolder.machines.doTerrainExplosion) {
```
Comment (DStrand1) [inline src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java:92]: If we have the config check in MTE, we can get rid of the check here

File: src/main/java/gregtech/common/ConfigHolder.java [hunk 14]
```diff
@@ -74,8 +74,12 @@ public static class MachineOptions {
         @Config.Comment({"Steam to EU multiplier for Steam Multiblocks.", "1.0 means 1L Steam -> 1 EU. 0.5 means 2L Steam -> 1 EU.", "Default: 0.5"})
         public double multiblockSteamToEU = 0.5;
 
-        @Config.Comment({"Whether machines should explode when overloaded with power.", "Default: true"})
-        public boolean doExplosions = true;
+        @Config.Comment({"Whether machines or boilers damage the terrain when they explode.",
+                "Note machines and boilers always explode when overloaded with power or met with special conditions, regardless of this config.", "Default: true"})
+        public boolean doExplosionDamagesTerrain = true;
```
Comment (DStrand1) [inline src/main/java/gregtech/common/ConfigHolder.java:79]: `doesExplosionDamageTerrain` ?

File: src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java [hunk 15]
```diff
@@ -60,7 +61,7 @@ protected ModularUI createUI(EntityPlayer entityPlayer) {
         int rowSize = (int) Math.sqrt(inventorySize);
 
         ModularUI.Builder builder = ModularUI.builder(GuiTextures.BACKGROUND, 176,
-                18 + 18 * rowSize + 94)
+                        18 + 18 * rowSize + 94)
```
Comment (DStrand1) [inline src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java:64]: Can you revert this, I think it may conflict with the ModularUI work and is a simple merge conflict to avoid

File: src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java [hunk 16]
```diff
@@ -58,6 +59,14 @@ public void renderMetaTileEntity(CCRenderState renderState, Matrix4 translation,
         }
     }
 
+    @Override
+    public void update() {
+        super.update();
+        if (ConfigHolder.machines.doTerrainExplosion) {
```
Comment (DStrand1) [inline src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java:65]: Can remove this config check as well if we check in MTE

**Comment by Quarri6343** [comment]
this will close #879 since I changed config description
