### PR TITLE
Pipe fixes

### LINKED ISSUE #1219: Item Pipe becomes null
### GregTech CEu Version

v2.4.1-beta

### Modpack Used

NomiFactory CEu v1.4.1a

### Addons Installed

_No response_

### Environment

Forge Server

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

image
Two conveyor belts extract silicon and sulfur from drawers into a pipe that outputs into an ender chest. A robot arm is attached to the output to make sure the ender chest always has 64 silicon and 64 sulfur inside.

### Actual Behavior

After some time, or perhaps a server reboot, the pipe stops working and starts throws out null errors in server logs.
[12:57:54] [Server thread/ERROR] [GregTech]: First PipeTile is null during walk at MutableBlockPos{x=-9, y=81, z=-25}

### Steps to Reproduce

1. Attach 2 conveyor belts to the same pipe which extract from 2 separate drawers, one containing silicon, and the other containing sulfur. 
2. Attach a robot arm on another side which outputs to an ender chest. The robot arm is configured to "Keep Exact" and an item filter with 64 sulfur and 64 silicon in the first two slots. 
3. Finally, restart the server.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by brachy84**
## What
- fixes a crash related to #1219 
- item pipes no longer tick (before endpoints did tick)
- replaced some data structures with fastutil ones for item pipe transfer
- fixes and closes #1219 (maybe)
- fixes a weird crash
- improves walker code

## Implementation Details
-

## Outcome
fixes and microoptimizations

## Additional Information
-

## Potential Compatibility Issues
-

### CODE REVIEW

File: src/main/java/gregtech/common/pipelike/cable/net/EnergyNetWalker.java [hunk 1]
```diff
@@ -18,6 +18,10 @@
 public class EnergyNetWalker extends PipeNetWalker {
 
     public static List<RoutePath> createNetData(World world, BlockPos sourcePipe) {
+        TileEntity te = world.getTileEntity(sourcePipe);
+        if (!(te instanceof TileEntityCable)) {
```
Comment (TechLord22) [inline src/main/java/gregtech/common/pipelike/cable/net/EnergyNetWalker.java:22]: You can in-line the `te` variable into the if statement here.

File: src/main/java/gregtech/common/pipelike/itempipe/net/ItemNetWalker.java [hunk 2]
```diff
@@ -26,6 +26,10 @@
 public class ItemNetWalker extends PipeNetWalker {
 
     public static List<ItemPipeNet.Inventory> createNetData(World world, BlockPos sourcePipe, EnumFacing faceToSourceHandler) {
+        TileEntity te = world.getTileEntity(sourcePipe);
+        if (!(te instanceof TileEntityItemPipe)) {
```
Comment (TechLord22) [inline src/main/java/gregtech/common/pipelike/itempipe/net/ItemNetWalker.java:30]: You can in-line the te variable into the if statement here.

File: src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipe.java [hunk 3]
```diff
@@ -97,25 +104,44 @@ public void resetTransferred() {
...
+                this.handlers.put(handler.getFacing(), handler);
+            }
+        }
+        if (itemPipe.defaultHandler != null) {
+            itemPipe.defaultHandler.updatePipe(this);
+            this.defaultHandler = itemPipe.defaultHandler;
         }
     }
+
+    private void checkTransferredState() {
```
Comment (TechLord22) [inline src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipe.java:129]: This method should be re-named to better describe its functionality.

**Review by TechLord22 — COMMENTED** [review]
You mentioned that with these changes, item pipe endpoints no longer tick. Individual pipe segments and endpoints with covers requiring ticking do still tick, correct?

File: src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipe.java (hunk 3 above)
Comment (brachy84) [reply src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipe.java:129]: That really is the best name i can think of

**Comment by brachy84** [comment]
> You mentioned that with these changes, item pipe endpoints no longer tick. Individual pipe segments and endpoints with covers requiring ticking do still tick, correct?

Thats correct.

File: src/main/java/gregtech/api/util/PerTickLongCounter.java [hunk 4]
```diff
@@ -1,24 +1,28 @@
 package gregtech.api.util;
 
-import net.minecraft.world.World;
+import java.util.function.LongSupplier;
 
 public class PerTickLongCounter {
```
Comment (Tictim) [inline src/main/java/gregtech/api/util/PerTickLongCounter.java:5]: I've noticed `PerTickLongCounter` is located in API package while `AveragingPerTickCounter` is not, we should probably move either one to another.

Personally I think moving `PerTickLongCounter` to non-API package is better, since it's not used in other API code and it doesn't provide a whole lot as an API.

**Comment by brachy84** [comment]
This might not fix #1219. I just added an earlier check, so nothing will ever get printed.

**Review by TechLord22 — APPROVED** [review]
