### PR TITLE
Reimplement some Crowbar behavior

### LINKED ISSUE #1422: Crowbar can't remove covers from pipes/wires
### GregTech CEu Version

1.12.2-2.5.0-beta

### Modpack Used

_No response_

### Addons Installed

_No response_

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Crowbar can remove covers from pipes/wires

### Actual Behavior

Crowbar does nothing when right clicking with it on a cover that is attached to a pipe or a wire

### Steps to Reproduce

1) Create new world or open an existing one
2) Place down a pipe or wire and attach any cover to it
3) Right click on that cover with a crowbar

### Additional Information

The crowbar can remove covers from any full block machines (crates too) as intended, but it plays the broken tool sound. I liked the old sound :(
Tested this on v2.4.5 and the issue is not reproducible there, looks like the tool rewrite broke something

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
## What
Reimplements some crowbar behavior missing after the tools PR.

Namely:
- Remove covers from Pipes
- Remove Frames from Framed Pipes

Closes #1422 

## Outcome
Reimplements some Crowbar Behavior.

### CODE REVIEW

File: src/main/java/gregtech/api/pipenet/block/BlockPipe.java [hunk 1]
```diff
@@ -354,6 +351,17 @@ public boolean onPipeActivated(World world, IBlockState state, BlockPos pos, Ent
             }
         }
 
+        if (itemStack.getItem().getToolClasses(itemStack).contains(ToolClasses.CROWBAR)) {
+            if (!world.isRemote) {
+                pipeTile.getCoverableImplementation().removeCover(coverSide);
```
Comment (LAGIdiot) [inline src/main/java/gregtech/api/pipenet/block/BlockPipe.java:356]: This functions returns `boolean` if it was successful. So you should work with it.

File: src/main/java/gregtech/common/blocks/BlockFrame.java [hunk 2]
```diff
@@ -185,6 +186,24 @@ public boolean replaceWithFramedPipe(World worldIn, BlockPos pos, IBlockState st
         return false;
     }
 
+    public boolean removeFrame(World world, BlockPos pos, IBlockState state, EntityPlayer player, ItemStack stack, EnumFacing facing) {
```
Comment (LAGIdiot) [inline src/main/java/gregtech/common/blocks/BlockFrame.java:189]: There is no need to pass in params you will not need

File: src/main/java/gregtech/common/blocks/BlockFrame.java [hunk 3]
```diff
@@ -185,6 +186,24 @@ public boolean replaceWithFramedPipe(World worldIn, BlockPos pos, IBlockState st
...
+
+        TileEntity te = world.getTileEntity(pos);
+        if (te instanceof IPipeTile && ((IPipeTile<?, ?>) te).getFrameMaterial() != null) {
+            TileEntityPipeBase<?, ?> pipeTile = (TileEntityPipeBase<?, ?>) te;
```
Comment (LAGIdiot) [inline src/main/java/gregtech/common/blocks/BlockFrame.java:193]: Here is potential bug waiting. Right now it won't happened as we don't have any other `IPipeTile` implementation which are not of type `TileEntityPipeBase` and could be here. But if there was one then `if` check would be `true` here but casting will return `null`. Leading to null reference expectation. So you should check for same value as you are going to cast to.

**Review by LAGIdiot — CHANGES_REQUESTED** [review]

File: src/main/java/gregtech/api/pipenet/block/BlockPipe.java (hunk 1 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/api/pipenet/block/BlockPipe.java:356]: The only case that this function could return false is if there is not a cover at the passed in side, which is something that is already checked for earlier in the method, therefore this would always return true.

Comment (LAGIdiot) [reply src/main/java/gregtech/api/pipenet/block/BlockPipe.java:353]: Yes, but if someone extracts this part to own function later use it here and reuse it somewhere else and does not check code 20 lines above it will generate bug. Same goes if some changes that code above without checking this part.

In all cases I would go with defensive programing. And add here that one if.

**Review by LAGIdiot — APPROVED** [review]
Good job! Approved with suggestion.
