### PR TITLE
Fix Fluid Jetpacks being caught on one fluid type

### LINKED ISSUE #1589: Liquid-Fueled Impeller Jetpack does not function with any other combustion fuel if you have used a Jetpack with a differing fuel type during a session
### GregTech CEu Version

2.5.4

### Modpack Used

Gregtech Community Pack 1.6.2

### Addons Installed

_No response_

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

That Jetpacks work with any combustion fuel type.

### Actual Behavior

The first fuel type that is used will be the only one that works correctly for the duration of the session. This persists over a world restart and the entire client must instead be restarted.

### Steps to Reproduce

Pick any combustion fuel type and fill a jetpack with it, use it. Now attempt to use a jetpack with a different fuel type and see that it fails.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
## What
This PR fixes Fluid Jetpacks being cached on one fluid type, in a temporary manor. Since there is an armor rewrite somewhat in progress, I applied a simple fix for now, leaving the logic to get revamped better in that PR.

Closes #1589

## Outcome
Fixes Fluid Jetpacks being caught on one fluid type

### CODE REVIEW

File: src/main/java/gregtech/common/EventHandlers.java [hunk 1]
```diff
@@ -194,6 +194,12 @@ public static void onLivingEquipmentChangeEvent(LivingEquipmentChangeEvent event
                 valueItem.isItemEqual(MetaItems.QUANTUM_CHESTPLATE_ADVANCED.getStackForm())) {
             event.getEntity().isImmuneToFire = false;
         }
+
+        // Workaround to recipe caching issue with fluid jetpack
+        // TODO, rewrite logic and remove in armor rewrite
+        if (valueItem.isItemEqual(MetaItems.SEMIFLUID_JETPACK.getStackForm())) {
```
Comment (TechLord22) [inline src/main/java/gregtech/common/EventHandlers.java:200]: Could prefer to use another method that compares the valueitems directly, instead of making a new ItemStack.

**Review by TechLord22 — APPROVED** [review]
