### PR TITLE
Fix crash when other mods register fluids with negative temperatures

### LINKED ISSUE #744: [BUG] Startup crash with GalaxySpace
**Describe the bug**
When GalaxySpace is installed with GTCEu, the game will fail to boot because the MetaFluids system throws Invalid temperature error
It does not happen if only GalactiCraft is installed with GTCEu

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar

**Setup**
start the game with the following modlist:
AsmodeusCore-1.12.2-0.0.29
CodeChickenLib-1.12.2-3.2.3.358-universal
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
GalaxySpace-1.12.2-2.0.17
gregtech-1.12.2-2.1.4-beta
MicdoodleCore-1.12.2-4.0.2.280

**Expected behavior**
The game boots

**Crash log**
[crash-2022-03-04_01.30.28-client.txt](https://github.com/GregTechCEu/GregTech/files/8179447/crash-2022-03-04_01.30.28-client.txt)

**Additional context**
For some reason, the game will boot if devtech-2.0.4 is present

### PR DESCRIPTION
**Pull request by TechLord22**
**What:**
Fixes crashes when other mods register fluids with the same name as GT's, but have negative temperatures.

**Outcome:**
Fixes #744.

### CODE REVIEW

File: src/main/java/gregtech/api/unification/material/properties/FluidProperty.java [hunk 1]
```diff
@@ -70,7 +70,12 @@ public FluidStack getFluid(int amount) {
     }
 
     public void setFluidTemperature(int fluidTemperature) {
-        Preconditions.checkArgument(fluidTemperature > 0, "Invalid temperature");
+        setFluidTemperature(fluidTemperature, true);
+    }
+
+    public void setFluidTemperature(int fluidTemperature, boolean isKelvin) {
+        if (isKelvin) Preconditions.checkArgument(fluidTemperature > 0, "Invalid temperature");
```
Comment (Rongmario) [inline src/main/java/gregtech/api/unification/material/properties/FluidProperty.java:77]: `>=`

**Review by Rongmario — CHANGES_REQUESTED** [review]

**Review by Rongmario — APPROVED** [review]
