### PR TITLE
Fix some issues with tape and maintenance hatches

### LINKED ISSUE #1657: Tape is deleted from maintenance hatches when loading world
### GregTech CEu Version

2.5.4-beta

### Modpack Used

_No response_

### Addons Installed

_No response_

### Environment

Singleplayer and Forge Server (both Linux)

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Tape should remain in maintenance hatches when reloading worlds

### Actual Behavior

Tape is deleted from maintenance hatches when reloading worlds

### Steps to Reproduce

1: Place a maintenance hatch or configurable maintenance hatch
2: Put tape inside the maintenance hatch
3: Leave world and load it again

### Additional Information

Reverting 651996a fixes this issue
Maintenance hatches also don't drop tape when broken
Maintenance hatches placed when using gtceu 2.5.0-beta that had tape at the time of updating will always have that much tape when the world loads, even if it is removed (i.e tape gets duplicated)

<details>
<summary>block data for a hatch placed in 2.5.0-beta</summary>

```
{
  id:"gregtech:machine",
  x:-537,
  y:93,
  z:971,
  ForgeCaps:{
    "nuclearcraft:capability_default_radiation_resistance":{
      radiationResistance:0.0d
    }
  },
  CustomName:"",
  MetaId:"gregtech:maintenance_hatch_configurable",
  MetaTileEntity:{
    FrontFacing:3,
    CachedLightValue:0,
  ImportInventory:[{
    Slot:0,
    id:"gregtech:meta_item_1",
    Count:12,
    Damage:502s
  }],
  ExportInventory:[],
  ImportFluidInventory:{
    TankAmount:0,
    Tanks:[]
  },
  ExportFluidInventory:{
    TankAmount:0,
    Tanks:[]
  },
  Covers:[],
  Fragile:0b,
  Muffled:0b,
  IsTaped:0b,
  DurationMultiplier:0.9d
  }
}
```
</details>
<details>
<summary>block data for a hatch placed in 2.5.4-beta:</summary>

```
{
  id:"gregtech:machine",
  x:-535,
  y:93,
  z:971,
  ForgeCaps:{
    "nuclearcraft:capability_default_radiation_resistance":{
      radiationResistance:0.0d
    }
  },
  CustomName:"",
  MetaId:"gregtech:maintenance_hatch_configurable",
  MetaTileEntity:{
    FrontFacing:3,
    CachedLightValue:0,
    ImportInventory:[],
    ExportInventory:[],
    ImportFluidInventory:{
      TankAmount:0,
      Tanks:[]
    },
    ExportFluidInventory:{
      TankAmount:0,
      Tanks:[]
    },
    Covers:[],
    Fragile:0b,
    Muffled:0b,
    IsTaped:0b,
    DurationMultiplier:0.9d
  }
}

```
</details>

for both examples, adding/removing tape does not change the block data in 2.5.4-beta

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
## What
This PR fixes some existing issues with tape and maintenance hatches mentioned in #1657 

Closes #1657 

## Implementation Details
The import handler override was removed as it was constantly creating a value in `importItems`, which would then write the contents to NBT, triggering the legacy NBT conversion, which was the cause of the tape duping on world load.

## Outcome
Fix some issues with tape and maintenance hatches

### CODE REVIEW

File: src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java [hunk 1]
```diff
@@ -429,6 +428,7 @@ public void readFromNBT(NBTTagCompound data) {
         // Legacy Inventory Handler Support
```
Comment (LAGIdiot) [inline src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java:428]: How much legacy this is and can it be thrown away?

Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java:428]: This is the old inventory contents stored in the NBT of the tile. It is legacy from the previous PR which transitioned to using a plain `ItemStackHandler` instead of the combined input and output inventories. 

It is safe to discard the NBT here, as the Inventory contents have already been read via NBT into the new system, and discarding the NBT here prevents this check from being hit again.

Comment (LAGIdiot) [reply src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java:428]: I see it is from 09.03.2023 so it is not legacy enough to throw it away.

Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java:428]: It is not being thrown away. The existing data is being converted into the new format, and then the key is being removed so that it does not attempt to convert into the new format again.

Comment (LAGIdiot) [reply src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java:428]: No, you miss understand me. I was thinking about having you to throw this whole legacy part away. As everyone should be converted already, but it is not legacy enough for it to be the case.

**Review by TechLord22 — APPROVED** [review]
