### PR TITLE
Fix Legacy Filter NBT Reading

### LINKED ISSUE #2569: Smart filter settings do not save between world loads
### GregTech CEu Version

2.8.11

### Modpack Used

_No response_

### Addons Installed

GCYM 1.3
GCYL: CEu 0.1.0 (latest version as of August 5th 2024, prereleases aren't numbered differently)

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Smart filter setting saves between world loads 

### Actual Behavior

Smart filters reset upon world load, i.e. they reset back to the first option "electrolyzer"

### Steps to Reproduce

1. place down crate (or other tile entity that supports filters as covers)
2. places smart filter on it (or robot arm with smart filter, both are broken)
3. configure to centrifuge or sifter setting
4. close world and then rejoin
5. smart filter will be set to electrolyzer

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ghzdude**
## What
Fixes #2569, along with properly handling the reading of legacy NBT. for filter as covers in particular, "FilterMode" is used for the filter cover mode, which conflicts with the smart item filter mode's NBT. oh and i also forgor to mark the cover as dirty on setting a stack in the simple item filter.

## Implementation Details
i used to rely on "FilterInventory" for checking if the incoming nbt was legacy, and sometimes calling both `deserializeNBT()` and `handleLegacyNBT()` at the same time. "IsBlacklist" is a better check because legacy NBT has it written outside of "Filter", whereas it is inside "Filter" currently.

## Outcome
legacy NBT is actually read correctly, and smart filter settings are saved.

## Additional Information
*i hate nbt*

### CODE REVIEW

File: src/main/java/gregtech/common/covers/CoverConveyor.java [hunk 1]
```diff
@@ -682,8 +682,12 @@ public void readFromNBT(@NotNull NBTTagCompound tagCompound) {
         this.distributionMode = DistributionMode.VALUES[tagCompound.getInteger("DistributionMode")];
         this.isWorkingAllowed = tagCompound.getBoolean("WorkingAllowed");
         this.manualImportExportMode = ManualImportExportMode.VALUES[tagCompound.getInteger("ManualImportExportMode")];
-        this.itemFilterContainer.deserializeNBT(tagCompound.getCompoundTag("Filter"));
-        this.itemFilterContainer.handleLegacyNBT(tagCompound.getCompoundTag("Filter"));
+        var filterTag = tagCompound.getCompoundTag("Filter");
+        if (filterTag.hasKey("IsBlacklist")) {
```
Comment (TechLord22) [inline src/main/java/gregtech/common/covers/CoverConveyor.java:686]: Is this converting the legacy tag into the new format? If so, should `IsBlacklist` be removed from the tag?

File: src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java [hunk 2]
```diff
@@ -201,9 +200,15 @@ public void deserializeNBT(NBTTagCompound nbt) {
     }
 
     public void handleLegacyNBT(NBTTagCompound nbt) {
-        if (hasFilter()) {
-            getFilter().getFilterReader().handleLegacyNBT(nbt);
+        // for filters as covers, the stack is set manually, and "FilterInventory" doesn't exist to be deserialized
+        // also, ItemStackHandler's deserialization doesn't use setStackInSlot, so I have to do that manually here
+        if (nbt.hasKey("FilterInventory")) {
```
Comment (TechLord22) [inline src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java:205]: Same question here.

File: src/main/java/gregtech/common/covers/CoverConveyor.java (hunk 1 above)
Comment (ghzdude) [reply src/main/java/gregtech/common/covers/CoverConveyor.java:686]: well, since "IsBlacklist" is written to a different place in the tag, this should only run once. i could remove the tag, but i don't see how that's useful.

File: src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java (hunk 2 above)
Comment (ghzdude) [reply src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java:205]: "FilterInventory" only exists when the cover used a FilterContainer (pumps, conveyors, etc). Filters as a cover only used the FilterWrapper, which does not have "FilterInventory" written to the tag. with the filter rework, "FilterInventory" is always written.

**Review by TechLord22 — APPROVED** [review]
