### PR TITLE
Fix bunch of issues

### LINKED ISSUE #707: [BUG] World corrupts with the Super Chest
**Describe the bug**
You can put a filled Super Chest(Quantum Chest) into an another Super Chest
repeating this will eventually corrupt your world with too big NBT

**Versions**
Versions
Forge: 14.23.5.2860
GTCE: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Setup**
SP/MP
_New world generated_

**Steps To Reproduce**
1)Fill your super chest with super chests filled with super chests
2)Repeat this

**Expected behavior**
super chests or quantum chests or super tanks or quantum tanks cannot be put into a super chest or a quantum chest

**Screenshots**
キャプチャ1123

### LINKED ISSUE #724: [BUG] The Quarktech™ Suit tooltip bugs
**Describe the bug**
・There is no tooltip mentions the Quarktech™ Suit Boots provides Jump Boost
・The Advanced Quarktech™ Suit Chestplate does not display "Hover mode" tooltip in JEI
This can lead the misunderstanding that it cannot hover

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Setup**
SP/MP
New world generated

**Screenshots**
キャプチャ1134
キャプチャ1133

### LINKED ISSUE #803: [BUG] Monitor Screen doesn't reflect changes when you swap your plugins
**Describe the bug**
After you swap your plugin in the Monitor Screen, the screen still behaves as the previous plugin is installed

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Setup**
SP
New world generated

**Steps To Reproduce**
1) setup the Central Monitor and put a plugin in the screen
2) click the plugin slot with an another plugin to swap it

**Expected behavior**
Monitor Screen should not display proxied GUI after the Online Pictures Plugin is installed

**Clips**

https://user-images.githubusercontent.com/39122497/158516174-eae4ec7d-aae4-4586-83bb-772826472e38.mp4

### LINKED ISSUE #807: [BUG] Blue Alloy Dust has no mixer recipe
**Describe the bug**
Red Alloy Dust has one so it is a bug

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Screenshots**
キャプチャ1211

### PR DESCRIPTION
**Pull request by Quarri6343**
**Implementation Details:**

- Monitor Screen will reload plugin when you swap it
- Blue Alloy now has mixer recipe
- Quarktech Suite now has proper tooltips
- Advanced Quarktech Suite now has hover mode tooltip in JEI
- You can no longer put an item with NBT into Super Chest

**Outcome:**
Fix #803 
Fix #807 
Fix #724 
Fix #707

### CODE REVIEW

File: src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java [hunk 1]
```diff
@@ -197,7 +197,14 @@ protected void initializeInventory() {
 
     @Override
     protected IItemHandlerModifiable createImportItemHandler() {
-        return new ItemStackHandler(1);
+        return new ItemStackHandler(1) {
+            @Override
+            public boolean isItemValid(int slot, @Nonnull ItemStack stack) {
+                NBTTagCompound compound = GTUtility.getOrCreateNbtCompound(stack);
```
Comment (DStrand1) [inline src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java:203]:
```suggestion
                NBTTagCompound compound = stack.getTagCompound();
```

**Review by DStrand1 — APPROVED** [review]
