### PR TITLE
CCQuad fix

### LINKED ISSUE #1678: Covers override lightmap coordinates provided by the blockstate's bakedmodel
### GregTech CEu Version

Dev

### Modpack Used

_No response_

### Addons Installed

_No response_

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Covers display emissive faces correctly; i.e. they use lightmap coordinates provided by the original bakedmodel.

### Actual Behavior

Well it's not doing it right

### Steps to Reproduce

amogus

### Additional Information

In both screenshot, the left two blocks are covered with no-light lamps, and the right two blocks are covered with regular lamps. The lightmap coordinates of the cover quads are overridden with CCL pipeline (presumably), which causes emissive effect of the cover to dim out in proportion to ambient light. Regular lamps do not get affected by this effect, possibly due to the fake world used in rendering, or some other obscure thing that I am not aware of.

### PR DESCRIPTION
**Pull request by Tictim**
## What
This PR corrects erroneous arithmetic operation in `CCQuad#pipe(IVertexConsumer)` that caused incorrect lighting effects on certain facade covers.

## Implementation Details
A new subtype of `CCQuad` is defined.

## Outcome
Fixes #1678

## Potential Compatibility Issues
None

### CODE REVIEW

File: src/main/java/gregtech/client/renderer/handler/FacadeRenderer.java [hunk 1]
```diff
@@ -327,4 +330,57 @@ private static double clampF(double x, Cuboid6 b, int j) {
...
+
+    private static List<CCQuad> fromArray(List<BakedQuad> bakedQuads) {
+        List<CCQuad> quads = new ArrayList<>();
+        for (BakedQuad quad : bakedQuads) {
+            quads.add(new FixedCCQuad(quad));
+        }
+        return quads;
+    }
+
+    private static class FixedCCQuad extends CCQuad {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/client/renderer/handler/FacadeRenderer.java:342]: Could we get a comment on why we have to do this?

**Review by ALongStringOfNumbers — APPROVED** [review]
Not yet tested in game
