### PR TITLE
Fix Filter Popup Panels deleting cached panel

### LINKED ISSUE #2716: Crash when clicking X to close Cover widget
### GregTech CEu Version

68f6e527cb6184c1f16d83685f3dd26ce632118b

### Modpack Used

_No response_

### Addons Installed

_No response_

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

- Robot arm on input bus, shove an item filter inside
- Click open the filter's config
- Press ESC, widget successfully closed
- Open it again, this time try clicking on the X Close button to close it
- Crashes the game

### Crash Report

https://mclo.gs/gmjts8b

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ghzdude**
## What
fixes #2716 
prevents filter popups from deleting their cached panel
also improves popup panel a bit

## Implementation Details
cached panel is deleted when the panel is closed instead of only in the button
the class is now public and replaced constructor parameters with builder methods
constructor is private
popup panel methods now return the popup panel class

## Outcome
filter popups can now be closed

### CODE REVIEW

File: src/main/java/gregtech/api/mui/GTGuis.java [hunk 1]
```diff
@@ -72,47 +72,81 @@ public static ModularPanel defaultPanel(MetaItem<?>.MetaValueItem valueItem) {
...
-        return new PopupPanel(name, width, height, disableBelow, closeOnOutsideClick);
+    public static PopupPanel createPopupPanel(String name, int width, int height, boolean deleteCachedPanel) {
+        return createPopupPanel(name, width, height)
+                .deleteCachedPanel(deleteCachedPanel);
     }
 
-    public static ModularPanel defaultPopupPanel(String name) {
-        return defaultPopupPanel(name, false, false);
+    public static PopupPanel defaultPopupPanel(String name) {
+        return new PopupPanel(name);
```
Comment (kumquat-ir) [inline src/main/java/gregtech/api/mui/GTGuis.java:86]: To actually set the default size on `defaultPopupPanel`, since it was removed in the constructor.
Other than this, looks good.
```suggestion
        return new PopupPanel(name).size(DEFAULT_WIDTH, DEFAULT_HEIGHT);
```

**Review by kumquat-ir — CHANGES_REQUESTED** [review]

**Review by kumquat-ir — APPROVED** [review]
