### PR TITLE
Recipe chart app fix

### LINKED ISSUE #1595: JEI Chart App crashing
### GregTech CEu Version

v2.5.4

### Modpack Used

GregTech Community Modpack v1.6.2

### Addons Installed

_No response_

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1) Use JEI Chart App in Terminal
2) Add SteamOven to Root node from preview page
3) Click on SteamOven on ingredient side (right side) -> ii creates new node which should contain SteamOven but it is empty
4) Click JEI focus button

### Crash Report

https://gist.github.com/LAGIdiot/d4d9c82595a1fca0e59ba23d82eeae97

### Additional Information

_No response_

### LINKED ISSUE #2007: [Bug] JEI button missing from machine recipe pages for JEI Charts terminal app
### GregTech CEu Version

MC 1.12 - GTCEu v2.6.0 and above

### Modpack Used

Nomifactory GTCEu edition 1.6  &  Vanilla GTCEu install (GTCEu + JEI)

### Addons Installed

_No response_

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Recipe chart allows JEI focus to put "+" button on all recipe pages or pages for machine crafting recipes (blacklisting the info pages).

### Actual Behavior

JEI focus is restricted to the default crafting tab and "+" button is unavailable on every other recipe tab as far as I can tell, making the app mostly unusable in the majority of recipe chains.

### Steps to Reproduce

Install any GTCEu version 1.6+ and JEI
Load up, give yourself a terminal from JEI menu, open JEI charts app.
You'll see JEI focus doesn't add buttons to any machine crafting pages.

### Additional Information

It is caused by [the second commit](https://github.com/GregTechCEu/GregTech/pull/1638/commits/3ed6bf0e13bfe206070a619c40ca76292cc9a87d) in this PR #1638 . The class has since been renamed to JustEnoughItemsModule.java in later versions of the mod.

### PR DESCRIPTION
**Pull request by brachy84**
## What
#1638 introduced a bug where only crafting recipes can be applied in the recipe chart. That PR was supposed to fix #1595.
That bug happened because of `0.0f / 0.0f = infinity` causing a int overflow which causes the item to be empty.
This pr fixes that by never dividing by anything less than 1. I also added a blacklist to jei to prevent certain jei categories to be applied to the recipe chart (like material tree or JEI info page).
I also cleaned the code a little bit up in `RGNode`.

## Implementation Details
Terminal magic

## Outcome
Undo #1638 and fix #1595 properly.
Closes #2007

## Additional Information
No

## Potential Compatibility Issues
Probably none

### CODE REVIEW

File: src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java [hunk 1]
```diff
@@ -127,9 +125,11 @@ public void register(IModRegistry registry) {
...
         ModularUIGuiHandler modularUIGuiHandler = new ModularUIGuiHandler(jeiHelpers.recipeTransferHandlerHelper());
         modularUIGuiHandler.setValidHandlers(widget -> !(widget instanceof CraftingSlotWidget));
-        if (Loader.isModLoaded(GTValues.MODID_JEI)) {
-            modularUIGuiHandler.setValidHandlers(widget -> !(widget instanceof CraftingSlotWidget) && widget instanceof ICraftingRecipeWrapper);
-        }
+        modularUIGuiHandler.blacklistCategory(
+                IntCircuitCategory.UID,
+                GTValues.MODID + ":material_tree",
+                VanillaRecipeCategoryUid.INFORMATION,
+                VanillaRecipeCategoryUid.FUEL);
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java:132]: This should probably also include the ore vein page and the fluid vein page

**Review by ALongStringOfNumbers — APPROVED** [review]
