### PR TITLE
Fusion Reactors lose heat when paused

### LINKED ISSUE #1777: Fusion Reactor soft malletting breaks game balance
### GregTech CEu Version

v2.6.2

### Modpack Used

GregTech Community Modpack v1.6.3 (updated GTCEu manually)

### Addons Installed

_No response_

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When you pause fusion reactor with soft mallet, its stored power level will be reset

### Actual Behavior

When you pause fusion reactor with soft mallet, it will save its power level so you can automate it very easily unlike GT5 or real science
it breaks the core mechanic of fusion reactor

### Steps to Reproduce

Run a fusion reactor and pause it with soft mallet

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
## What
This PR changes fusion reactors to additionally lose heat when they are soft malleted, instead of just when they are not running recipes. Closes #1777

## Outcome
Fusion Reactors now lose heat when soft malleted.

### CODE REVIEW

File: src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java [hunk 1]
```diff
@@ -323,7 +324,7 @@ protected long getMaxVoltage() {
         @Override
         public void updateWorkable() {
             super.updateWorkable();
-            if (!isActive && heat > 0) {
+            if (!(isActive || isWorkingEnabled()) && heat > 0) {
```
Comment (TechLord22) [inline src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java:327]: Would `!recipeMapWorkable.isWorking() && heat > 0` be preferred instead here, so heat is also lost when there is not enough energy as well?

**Review by TechLord22 — APPROVED** [review]
