### PR TITLE
Fix Stocking Buses running recipes while offline

### LINKED ISSUE #2559: Multiblock keeps running without consuming input when ME Stocking Input Bus/Hatch is disconnected
### GregTech CEu Version

v2.8.10

### Modpack Used

_No response_

### Addons Installed

AE2 Unofficial Extended Life v0.56.6
Had Enough Items 4.25.4

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

When an ME Stocking Input Bus/Hatch is disconnected, the multiblock can no longer use items from the ME network. As a result, it should turn off after finishing the current recipe.

### Actual Behavior

The multiblock continues to run. Inputs required by the recipe are not consumed in the ME network. As a consequence, output is duplicated.

### Steps to Reproduce

https://github.com/user-attachments/assets/31070fd1-01c2-472f-af2d-8ca992c6b6d2

Set up some multiblocks for testing and connect them to an ME network. 
Use ME Stocking Input Bus/Hatch for all multiblock inputs.

1. Configure the ME Stocking Input Bus/Hatch to provide recipe inputs.
2. Multiblock starts running. Inputs are consumed from the ME network.
3. Remove the cable connected to the ME Stocking Input Bus/Hatch or turn off the ME network.
4. Multiblock continues to run. Inputs are not consumed from the ME network. Outputs are created out of nothing.

### Additional Information

- The bug does not occur with the ME Input Bus/Hatch (the non-stocking version).
- #2530 could be due to this, if the ME network loses power.

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
## What
Fixes Stocking buses/hatches running recipes while they are offline.

Closes #2559

## Implementation Details
Immediately resync the inventory if the online status of the network changes

## Outcome
Fixes Stocking buses being able to provide inputs to multiblocks while they are offline.

### CODE REVIEW

**Review by TechLord22 — APPROVED** [review]

**Review by IntegerLimit — COMMENTED** [review]
If offline, wouldn't it just be simpler and cleaner to clear the item slots instead of performing a full refresh, such as its done in [Labs](https://github.com/Nomi-CEu/Nomi-Labs/blob/main/src/main/java/com/nomiceu/nomilabs/mixin/gregtech/MetaTileEntityMEStockingBusMixin.java#L45-L56)?

File: src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java [hunk 1]
```diff
@@ -64,9 +64,22 @@ protected ExportOnlyAEStockingItemList getAEItemHandler() {
...
+        if (!getWorld().isRemote) {
+            if (isWorkingEnabled() && autoPull && getOffsetTimer() % 100 == 0) {
+                refreshList();
+                syncME();
+            }
+
+            // Immediately clear cached items if the status changed, to prevent running recipes while offline
+            if (this.meStatusChanged && !this.isOnline) {
+                if (autoPull) {
+                    clearInventory(0);
```
Comment (TechLord22) [inline src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java:76]: Can this use `getAEItemHandler().clearConfig()`? If so maybe this and other occurrences of `clearInventory(0)` should move to it.

**Review by TechLord22 — APPROVED** [review]

File: src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java (hunk 1 above)
Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java:76]: They do basically the same thing, so I don't see a particular reason to switch.
