### PR TITLE
Yet another Crafting station fix PR

### LINKED ISSUE #1235: The server has stopped responding!
### GregTech CEu Version

gregtech-1.12.2-2.4.1-beta

### Modpack Used

nomi-ceu

### Addons Installed

_No response_

### Environment

Catserver

### Side Crashed

Server

### New Worlds

No

### Steps to Reproduce

RecipeMatcher.backtrack

### Crash Report

[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: The server has stopped responding!
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: Spigot version: git-CatServer-1.12.2-8d58cdb8 (MC: 1.12.2)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: Memory using: 1502MB/4096MB/5000MB
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: Server thread dump (Look for plugins here before reporting to Spigot!):
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: Current Thread: Server thread
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	PID: 39 | Suspended: false | Native: false | State: RUNNABLE
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	Stack:
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.backtrack(RecipeMatcher.java:151)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.common.util.RecipeMatcher.findMatches(RecipeMatcher.java:85)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraftforge.oredict.ShapelessOreRecipe.func_77569_a(ShapelessOreRecipe.java:126)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.common.metatileentities.storage.CachedRecipeData.getIngredientEquivalent(CachedRecipeData.java:83)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.common.metatileentities.storage.CachedRecipeData.attemptMatchRecipe(CachedRecipeData.java:32)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.common.metatileentities.storage.CraftingRecipeLogic.isRecipeValid(CraftingRecipeLogic.java:161)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.common.gui.widget.craftingstation.CraftingSlotWidget.detectAndSendChanges(CraftingSlotWidget.java:149)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.gui.widgets.AbstractWidgetGroup.detectAndSendChanges(AbstractWidgetGroup.java:239)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.gui.widgets.AbstractWidgetGroup.detectAndSendChanges(AbstractWidgetGroup.java:239)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.gui.impl.ModularUIContainer$$Lambda$3794/902253092.accept(Unknown Source)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		com.google.common.collect.ImmutableMapKeySet.lambda$forEach$0(ImmutableMapKeySet.java:72)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		com.google.common.collect.ImmutableMapKeySet$$Lambda$3637/804821055.accept(Unknown Source)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		com.google.common.collect.RegularImmutableBiMap$Inverse.lambda$forEach$0(RegularImmutableBiMap.java:205)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		com.google.common.collect.RegularImmutableBiMap$Inverse$$Lambda$3638/518138828.accept(Unknown Source)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		com.google.common.collect.RegularImmutableBiMap.forEach(RegularImmutableBiMap.java:153)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		com.google.common.collect.RegularImmutableBiMap$Inverse.forEach(RegularImmutableBiMap.java:205)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		com.google.common.collect.ImmutableMapKeySet.forEach(ImmutableMapKeySet.java:72)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.gui.impl.ModularUIContainer.func_75132_a(ModularUIContainer.java:112)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.gui.UIFactory.openUI(UIFactory.java:64)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.metatileentity.MetaTileEntity.onRightClick(MetaTileEntity.java:400)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.metatileentity.MetaTileEntity.onCoverRightClick(MetaTileEntity.java:373)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		gregtech.api.block.machines.BlockMachine.func_180639_a(BlockMachine.java:338)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:555)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1157)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.util.Util.func_181617_a(SourceFile:529)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[11:04:49] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.lang.Thread.run(Thread.java:745)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by PrototypeTrousers**
## What
Yet another Crafting Station Issue F I X.
This time fix the issue with Shapeless Recipes Murdering the server performance, when the Crafting Station is surrounded by inventories with many slots
Also made recipe re-matching stricter to avoid issue with recipes with NBT-dependent inputs not correctly updating the output.
(Like potion arrows)

## Implementation Details
Implement a cache for the tested stacks for the current recipe while also testing them individually against the ingredients before calling the recipe matches() method to avoid the recursion of Shapeless recipes

## Outcome
Game is playable while a shapeless recipe is on the crafting station's crafting grid

## Additional Information
Fixes #1235, and hopefully #935

## Potential Compatibility Issues
_This section is for defining possible compatibility issues. It must be used when there are API changes, item/block/material/machine changes, or recipe changes._

**Please fill in as much useful information as possible. Also, please remove all unused sections, including this and the other explanations.**

### CODE REVIEW

File: src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java [hunk 1]
```diff
@@ -74,17 +78,47 @@ public boolean getIngredientEquivalent(int slot) {
...
+            }
+            if (!matched) {
+                map.put(itemStackKey, false);
+                continue;
+            }
+
             //update item in slot, and check that recipe matches and output item is equal to the expected one
             inventory.setInventorySlotContents(slot, itemStack);
-            if (recipe.matches(inventory, itemSources.getWorld())) {
+            if (recipe.matches(inventory, itemSources.getWorld()) && ItemStack.areItemStacksEqual(recipe.getCraftingResult(inventory), previousStack)) {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java:114]: Do we want to check the Equality before checking `matches`, so that we might be able to avoid more matches calls?

Comment (PrototypeTrousers) [reply src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java]: theres only one IRecipe instance here; the getCraftingResult method should also return a copy of the itemstack in the output

**Review by ALongStringOfNumbers — APPROVED** [review]
