### PR TITLE
Fix Chainsaw not playing sound when breaking ice

### LINKED ISSUE #1746: Breaking Ice with Chainsaw does not play Sound
### GregTech CEu Version

v2.6.1

### Modpack Used

GregTech Community Modpack v1.6.3

### Addons Installed

_No response_

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Breaking Ice with Chainsaw in GT5 plays chainsaw sound iirc

### Actual Behavior

it does not
(if you break ice while sneaking the sound is played but it applies to every block)

### Steps to Reproduce

1) break ice with chainsaw

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by DStrand1**
Closes #1746

### CODE REVIEW

File: src/main/java/gregtech/common/ToolEventHandlers.java [hunk 1]
```diff
@@ -154,6 +155,10 @@ public static void onHarvestDrops(@Nonnull BlockEvent.HarvestDropsEvent event) {
                         // only try once, so future water placement does not get eaten too
                         return false;
                     });
+                    IGTTool igtTool = (IGTTool) stack.getItem();
+                    if (igtTool.canPlaySound(stack) && igtTool.getSound() != null) {
+                        player.world.playSound(null, player.posX, player.posY, player.posZ, igtTool.getSound(), SoundCategory.BLOCKS, 1.0F, 1.0F);
```
Comment (TechLord22) [inline src/main/java/gregtech/common/ToolEventHandlers.java:160]:
```suggestion
                    if (igtTool.canPlaySound(stack)) {
                        igtTool.playSound(player);
```

**Review by TechLord22 — APPROVED** [review]
