### PR TITLE
Minor Digital Interface Cover tweaks

### LINKED ISSUE #725: [BUG] the Digital Interface Cover UI has no border
**Describe the bug**
When the Battery Buffer has negative amount of energy (#716 ),
the Digital Interface Cover UI will be broken and expands infinitely since there is no absolute border of it
It also happens with the Central Monitor displaying the same cover

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Setup**
SP/MP
New world generated

**Steps To Reproduce**
1.put a UHV 16A Battery Buffer
2.put two filled Ultimate Batteries into it
3.put a Digital Interface Cover and configure it to display energy

**Expected behavior**
The Digital Interface Cover displays energy within one block

**Screenshots**
キャプチャ1132

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
**What:**
This PR makes minor tweaks to the Digital Interface cover.

The first tweak is that when in item/fluid mode, the slot selected will no longer be unbounded and able to be increased infinitely, rather it is bound by the maximum number of slots/tanks in the machine, and will wrap around from max slot -> first slot and vice-versa.

The second tweak is the clamp the width of the rendered energy bar, in so Fixes #725. The entire energy portion still does not quite function correctly when energy values overflow Long.MAX_VALUE, but I will leave that for another PR to fix, and simply fix the rendering issue.

**Outcome:**
Makes minor tweaks to the Digital Interface Cover

### CODE REVIEW

File: src/main/java/gregtech/common/covers/CoverDigitalInterface.java [hunk 1]
```diff
@@ -302,6 +302,11 @@ public EnumActionResult onRightClick(EntityPlayer playerIn, EnumHand hand, Cuboi
             lastClickUUID = playerIn.getPersistentID();
             if (playerIn.isSneaking() && playerIn.getHeldItemMainhand().isEmpty()) {
                 if (rayTraceResult != null && rayTraceResult.typeOfHit == RayTraceResult.Type.BLOCK) {
+                    int maxSlotLimit = 0;
```
Comment (Yefancy) [inline src/main/java/gregtech/common/covers/CoverDigitalInterface.java:305]: maxSlotLimit = Integer.MAX_VALUE; // should work if this.coverholder not a mte,

**Review by Yefancy — APPROVED** [review]
