### PR TITLE
Fix Quantum Chest item voiding

### LINKED ISSUE #1736: Super and quantum chest void input item if output slot has almost 64 items
### GregTech CEu Version

v2.6.1

### Modpack Used

Nomifactory CEu v1.6.1-alpha-1 (Expert Mode)

### Addons Installed

GTFO v1.9.1

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

When a machine output item into super or quantum chest, item will not be void in any circumstances

### Actual Behavior

If the recipe that has output amount is an even number, the item amount in the super chest will be the same:
Example: 64 iron rings -> 128 wrought iron nugget (Arc Furnace Recipe)

https://user-images.githubusercontent.com/111768452/235629967-6caace54-a482-453a-b231-0afd7feba101.mp4

If the recipe that has output amount is an odd number, the item is be void when output slot of the chest is almost 64 and back to normal when the text 'Item Amount' not show 0:
Example: 3x64 of Sodium Hydroxide Dust -> 5x64 Sodium Nitrate Dust

https://user-images.githubusercontent.com/111768452/235634290-b09cc7f8-2096-407f-933b-065d95047cf1.mp4

Sodium Ruthenate Dust-> Ruthenium Tetroxide Dust

https://user-images.githubusercontent.com/111768452/235650552-3169c4bd-92c8-41a7-a74c-c523ecd30830.mp4

This bug only occur when the machine is pushing item and running recipe at the same time

### Steps to Reproduce

1) Put a super or quantum chest next to a machine (or output bus)
2) Turn on auto item output and configure the machine hatch to the chest
3) Run any recipe that has the output amount is an odd number

### Additional Information

I'm not good at English so some of my sentence might not be understandable
Also, I didn't test on recipe that has 2 different item output

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
## What
Fixes Quantum Chest item voiding. Closes #1736 

This was happening because in cases where the initial virtualized items were being set up, we were not inserting the non-virtualized items into the output slot

## Outcome
Fixes quantum chest item voiding when setting up virtual items

### CODE REVIEW

File: src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java [hunk 1]
```diff
@@ -526,63 +526,78 @@ public ItemStack extractItem(int slot, int amount, boolean simulate) {
...
+                        ItemStack virtualStack = insertedStack.copy();
+                        virtualStack.setCount(virtualizedAmount);
+                        MetaTileEntityQuantumChest.this.itemStack = virtualStack;
+                        MetaTileEntityQuantumChest.this.itemsStoredInside = virtualizedAmount;
+                    } else {
+                        MetaTileEntityQuantumChest.this.itemsStoredInside += virtualizedAmount;
+                    }
+
+                    if (amountInsertedIntoExport != 0) {
+                        ItemStack insertedStackCopy = insertedStack.copy();
```
Comment (TechLord22) [inline src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java:590]: Why is a copy needed here?

File: src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java [hunk 2]
```diff
@@ -526,63 +526,78 @@ public ItemStack extractItem(int slot, int amount, boolean simulate) {
...
+                        insertedStackCopy.setCount(amountInsertedIntoExport);
+                        MetaTileEntityQuantumChest.this.exportItems.insertItem(0, insertedStackCopy, simulate);
```
Comment (TechLord22) [inline src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java:592]: Do we need to account for items that could not fit in the export slot?

File: src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java [hunk 3]
```diff
@@ -526,63 +526,78 @@ public ItemStack extractItem(int slot, int amount, boolean simulate) {
...
+                    }
+                    return insertedStack;
+                }
+                else {
+                    MetaTileEntityQuantumChest.this.itemsStoredInside += remainingStack.getCount();
```
Comment (TechLord22) [inline src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java:597]: Is this safe to do? What happens when this value exceeds the maximum storage amount in the chest?

Comment (ALongStringOfNumbers) [reply src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java:597]: This will not happen, as `remainingStack` has its count stack size limited by the amount of room left for items to be virtualized

**Review by serenibyss — APPROVED** [review]
