### PR TITLE
Apply recipe modifications in dedicated stages

### LINKED ISSUE #1676: Configurable maintenance hatch not working when energy hatch tier is lower than the recipe tier
### GregTech CEu Version

2.5.4

### Modpack Used

just GTCEu + JEI & one probe

### Addons Installed

_No response_

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Configurable maintenance hatch should affect duration of any recipe in the multiblock, regardless of tier or the energy hatches used

### Actual Behavior

when running recipe at some tier (for example MV) with energy hatches of lower tier (2 LV Hatches pushing multiblock to MV) the duration cut/extend on Configurable maintenance hatch stops working. For example EBF smelting aluminium with MV energy hatch works just fine, but swapping the hatch to 2 LV hatches makes it so configurable maintenance hatch doesnt affect the recipe duration

### Steps to Reproduce

1. Build an EBF with MV energy hatch and put some aluminium to smelt. Maintenance hatch properly affects recipe duration as shown on one probe and measured with real life timer:
image
(hatch set to 1.0 duration and having the defualt 44s duration)
image
(hatch set to 0.9 cutting duration to 40s)

2. Swap the MV hatch for 2 LV hatches. Now the duration set in maintenance hatch has no effect (measured with timer to make sure it's not just visual bug on one probe)
image
image
(the recipe is back to the default 44s duration despite hatch being set to 0.9)

Same happens in different machines with only 1 hatch. For example on Pyrolyse oven with 1 MV hatch the recipe properly gets cut from 16s to 14s:
image
(hatch on 1.0 with 16s duration)
image
(hatch on 0.9 with 14s duration)

Swapping to LV hatch makes so the duration is not affected (recipe goes back to the default 32s since its not overclocked)
image
image
(recipe is 32s whether it's set to 0.9 / 1.0 / 1.1)

Also tested the same scenario for different tier recipes like Nichrome (2 MV hatches preventing duration cut but 1 HV hatch works fine) and Tungsten (2 HV hatches preventing duration cut but 1 EV hatch working fine)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TechLord22**
## What
This PR modifies recipe logic to apply modifications to the recipe in separate phases: pre-overclock, overclocking, and post-overclock. Pre and Post are always called, but overclocking is not.

First, it moves the maintenance hatch pentalies to the pre and post-overclock phases. This will prevent overrides of overclocking-related methods from failing to apply these values. The configurable maintenance hatch duration bonuses are applied pre-overclock, and maintenance duration penalties are made post-overclock. This fixes #1676.

Next, it moves the calculation for the amount of overclocks to perform into a separate method. This reduces a lot of duplicated code across the variations of recipe logic. Doing so also allows the PA to no longer need to override `calculateOverclock(Recipe)`. 

Heating coil logic has been fixed to respect maintenance hatch values as well. The EUt reduction bonus from coils is also now applied in the pre-overclock phase, instead of in the overclocking method itself. 

## Outcome
Refactors recipe value modification to prevent large code copy pastes. Fixes #1676.

## Potential Compatibility Issues
This PR removes/renames `performNonOverclockBonuses(int[])` and replaces it with `modifyOverclockPost(int[], IRecipePropertyStorage)`. It also removes `checkCanOverclock(int)`. Addons calling these old methods will need updating.

Additionally, addons with overrides of other recipe logic functions may no longer behave the same. They will want/need to refactor their own logic to utilize the new methods, to ensure their behavior is unaffected.

### CODE REVIEW

**Review by bruberu — APPROVED** [review]
The changes look reasonable, and testing in game found no weird issues with the PA or EBF.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java [hunk 1]
```diff
@@ -251,43 +249,37 @@ protected boolean prepareRecipeDistinct(Recipe recipe) {
...
+        super.modifyOverclockPost(overclockResults, storage);
 
-        if (maintenanceValues.getFirst() > 0)
-            overclock[1] = (int) (overclock[1] * (1 + 0.1 * maintenanceValues.getFirst()));
+        // apply maintenance penalties
+        Tuple<Integer, Double> maintenanceValues = getMaintenanceValues();
 
-        return overclock;
+        // duration penalty
+        if (maintenanceValues.getFirst() > 0) {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:272]: According to your PR statement, the EU changes were supposed to be made post overclock, not the duration changes.  Is that still accurate and this logic is wrong? As currently you are modifiying the duration pre and post overclock, and not touching the EU

File: src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java [hunk 2]
```diff
@@ -635,48 +629,53 @@ protected int[] calculateOverclock(@Nonnull Recipe recipe) {
         return overclockResult;
     }
 
-    /**
-     * @param recipeEUt the EU/t of the recipe attempted to be run
-     * @return true if the recipe is able to overclock, else false
-     */
-    protected boolean checkCanOverclock(int recipeEUt) {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java:642]: Why exactly was this removed? It seems fine to still call it after the added `modifyOverclockPre`

File: src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java [hunk 3]
```diff
@@ -19,29 +16,34 @@ public MultiblockFuelRecipeLogic(RecipeMapMultiblockController tileEntity) {
...
+    @Nonnull
     @Override
     protected int[] runOverclockingLogic(@Nonnull IRecipePropertyStorage propertyStorage, int recipeEUt, long maxVoltage, int recipeDuration, int amountOC) {
+        // no overclocking happens other than parallelization,
+        // so return the recipe's values, with EUt made positive for it to be made negative later
+        return new int[]{-recipeEUt, recipeDuration};
+    }
+
+    @Override
+    protected void modifyOverclockPre(@Nonnull int[] values, @Nonnull IRecipePropertyStorage storage) {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java:28]: Should this call super like the other calls?

File: src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java [hunk 4]
```diff
@@ -19,29 +16,34 @@ public MultiblockFuelRecipeLogic(RecipeMapMultiblockController tileEntity) {
...
+
+        // duration bonus
+        if (maintenanceValues.getSecond() != 1.0) {
+            values[1] = (int) Math.round(values[1] / maintenanceValues.getSecond());
         }
+    }
 
-        overclock[1] = (int) (overclock[1] * (1 - 0.1 * numMaintenanceProblems));
+    @Override
+    protected void modifyOverclockPost(int[] overclockResults, @Nonnull IRecipePropertyStorage storage) {
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java:39]: Should this call super like the other calls?

File: src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java [hunk 5]
```diff
@@ -19,29 +16,34 @@ public MultiblockFuelRecipeLogic(RecipeMapMultiblockController tileEntity) {
...
-                overclock = new int[]{recipeEUt * -1, (int) Math.round(recipeDuration / durationMultiplier)};
-            }
-        }
-        if (overclock == null) {
-            overclock = new int[]{recipeEUt * -1, recipeDuration};
+        Tuple<Integer, Double> maintenanceValues = getMaintenanceValues();
+
+        // duration bonus
+        if (maintenanceValues.getSecond() != 1.0) {
+            values[1] = (int) Math.round(values[1] / maintenanceValues.getSecond());
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java:34]: maintenanceValues.getSecond is supposed to be a duration multiplier, so why is the duration being divided here? Was this an issue with the original code?

File: src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java [hunk 6]
```diff
@@ -58,27 +58,28 @@ public static int[] standardOverclockingLogic(int recipeEUt, long maxVoltage, in
...
-     * @param amountEUtDiscount the amount of discounts to apply
+     * @param providedTemp the temperate provided by the machine
+     * @param requiredTemp the required temperature of the recipe
      * @return the discounted EU/t
      */
-    public static int applyCoilEUtDiscount(int recipeEUt, int amountEUtDiscount) {
+    public static int applyCoilEUtDiscount(int recipeEUt, int providedTemp, int requiredTemp) {
+        if (requiredTemp < OverclockingLogic.COIL_EUT_DISCOUNT_TEMPERATURE) return recipeEUt;
+        int amountEUtDiscount = OverclockingLogic.calculateAmountCoilEUtDiscount(providedTemp, requiredTemp);
         if (amountEUtDiscount < 1) return recipeEUt;
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java:76]: This line is now unneeded, as you check the required temp earlier now.

**Review by ALongStringOfNumbers — COMMENTED** [review]
Kinda confused with the new system, as currently maintenance duration modifications are being applied pre and post overclock

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java (hunk 1 above)
Comment (TechLord22) [reply src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:272]: EU was a misinterpretation on my part. I updated the PR description to reflect this. The changes made pre-oc are the bonus duration from the configurable maintenance hatch. The changes post-oc are the duration penalties from unfixed maintenance problems.

File: src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java (hunk 2 above)
Comment (TechLord22) [reply src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java:642]: This method became extraneous with the refactors, due to `getNumberOfOCs()`. The method covers the checks for `!isAllowOverclocking()`, `overclockTier <= GTValues.LV`, as well as `overclockTier > recipeTier`.

File: src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java (hunk 3 above)
Comment (TechLord22) [reply src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java:28]: This should not. Fuel logic needs the duration to act opposite to how regular recipes operate.

A regular recipe having a duration decrease makes it faster, but with a generator would produce less energy, so instead the generator uses division to make it longer, therefore producing more power instead.

The inverse is also true, a longer recipe multiplier from the hatch should make generators have a shorter recipe (less power generated) in exchange for the bonus.

File: src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java (hunk 5 above)
Comment (TechLord22) [reply src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java:34]: The original code also used division. See my reply to your other comment on this method for why.

File: src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java (hunk 4 above)
Comment (TechLord22) [reply src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java:39]: See my explanation for the comments in `modifyOverclockPre`.

File: src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java (hunk 6 above)
Comment (TechLord22) [reply src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java:76]: This line is technically unneeded to achieve the same result, but is still useful as an early exit. 

For example, in a scenario such as providedTemp=901, and requiredTemp=900: 
The first if statement would be false, since `900 < COIL_EUT_DISCOUNT_TEMPERATURE = 900 < 900 = false`.

Then call `calculateAmountCoilEUtDiscount()` would be called. That method would return 0 in this case, since `(901 - 900) / 900 = 0`.

Then if statement is checked to skip the math at the end, since any number to the 0th power is 1, which would not modify the EUt.

File: src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java [hunk 7]
```diff
@@ -251,43 +249,37 @@ protected boolean prepareRecipeDistinct(Recipe recipe) {
     }
 
     @Override
-    protected int[] runOverclockingLogic(@Nonnull IRecipePropertyStorage propertyStorage, int recipeEUt, long maxVoltage, int recipeDuration, int amountOC) {
+    protected void modifyOverclockPre(@Nonnull int[] values, @Nonnull IRecipePropertyStorage storage) {
+        super.modifyOverclockPre(values, storage);
+
         // apply maintenance penalties
```
Comment (ALongStringOfNumbers) [inline src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java:255]: This comment needs to be changed, as it is no longer correct.

**Review by ALongStringOfNumbers — APPROVED** [review]
